// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: kv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_ADD    Operation = 0
	Operation_UPDATE Operation = 1
	Operation_DELETE Operation = 2
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "ADD",
		1: "UPDATE",
		2: "DELETE",
	}
	Operation_value = map[string]int32{
		"ADD":    0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

type KeyInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyInput) Reset() {
	*x = KeyInput{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInput) ProtoMessage() {}

func (x *KeyInput) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInput.ProtoReflect.Descriptor instead.
func (*KeyInput) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *KeyInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SetInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInput) Reset() {
	*x = SetInput{}
	mi := &file_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInput) ProtoMessage() {}

func (x *SetInput) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInput.ProtoReflect.Descriptor instead.
func (*SetInput) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{2}
}

func (x *SetInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetInput) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LengthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        uint64                 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LengthResponse) Reset() {
	*x = LengthResponse{}
	mi := &file_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LengthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LengthResponse) ProtoMessage() {}

func (x *LengthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LengthResponse.ProtoReflect.Descriptor instead.
func (*LengthResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{3}
}

func (x *LengthResponse) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=kv.Operation" json:"operation,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{4}
}

func (x *Change) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_ADD
}

func (x *Change) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\x12\x02kv\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n" +
	"\bKeyInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"3\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"2\n" +
	"\bSetInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"(\n" +
	"\x0eLengthResponse\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x04R\x06length\"K\n" +
	"\x06Change\x12+\n" +
	"\toperation\x18\x01 \x01(\x0e2\r.kv.OperationR\toperation\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value*,\n" +
	"\tOperation\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\xab\x02\n" +
	"\x02KV\x12&\n" +
	"\x03Get\x12\f.kv.KeyInput\x1a\x0f.kv.GetResponse\"\x00\x12-\n" +
	"\x03Set\x12\f.kv.SetInput\x1a\x16.google.protobuf.Empty\"\x00\x120\n" +
	"\x06Delete\x12\f.kv.KeyInput\x1a\x16.google.protobuf.Empty\"\x00\x126\n" +
	"\x06Length\x12\x16.google.protobuf.Empty\x1a\x12.kv.LengthResponse\"\x00\x129\n" +
	"\x05Clear\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12)\n" +
	"\tSubscribe\x12\f.kv.KeyInput\x1a\n" +
	".kv.Change\"\x000\x01B!Z\x1fgithub.com/y7ls8i/kv/grpc/protob\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kv_proto_goTypes = []any{
	(Operation)(0),         // 0: kv.Operation
	(*KeyInput)(nil),       // 1: kv.KeyInput
	(*GetResponse)(nil),    // 2: kv.GetResponse
	(*SetInput)(nil),       // 3: kv.SetInput
	(*LengthResponse)(nil), // 4: kv.LengthResponse
	(*Change)(nil),         // 5: kv.Change
	(*emptypb.Empty)(nil),  // 6: google.protobuf.Empty
}
var file_kv_proto_depIdxs = []int32{
	0, // 0: kv.Change.operation:type_name -> kv.Operation
	1, // 1: kv.KV.Get:input_type -> kv.KeyInput
	3, // 2: kv.KV.Set:input_type -> kv.SetInput
	1, // 3: kv.KV.Delete:input_type -> kv.KeyInput
	6, // 4: kv.KV.Length:input_type -> google.protobuf.Empty
	6, // 5: kv.KV.Clear:input_type -> google.protobuf.Empty
	1, // 6: kv.KV.Subscribe:input_type -> kv.KeyInput
	2, // 7: kv.KV.Get:output_type -> kv.GetResponse
	6, // 8: kv.KV.Set:output_type -> google.protobuf.Empty
	6, // 9: kv.KV.Delete:output_type -> google.protobuf.Empty
	4, // 10: kv.KV.Length:output_type -> kv.LengthResponse
	6, // 11: kv.KV.Clear:output_type -> google.protobuf.Empty
	5, // 12: kv.KV.Subscribe:output_type -> kv.Change
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		EnumInfos:         file_kv_proto_enumTypes,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
